kind: ConfigMap
apiVersion: v1

metadata:
  name: easyshop-configmap
  namespace: easyshop-ns

data:
  MONGODB_URI: mongodb://mongodb-service:27017/easyshop
  NODE_ENV: production
  NEXT_PUBLIC_API_URL: http://54.167.112.59/api  
  NEXTAUTH_URL: http://54.167.112.59
